name: publish
on: [push]
jobs:
  publish-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push the backend Docker image
        run: |
          cd Backend
          docker build . --tag ghcr.io/jonathanxdr/note-library-backend:latest
          docker push ghcr.io/jonathanxdr/note-library-backend:latest
